name: FastFail Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]
    paths: ["**.cs", "**.yml", "**.csproj"]
  workflow_dispatch:

jobs:
  FF-BUILD-PIPELINE:
    runs-on: windows-latest
    env:
      SLN: ${{ github.workspace }}\FailFast\FailFast.sln
      TESTPRJ: ${{ github.workspace }}\FailFast\UnitTests\UnitTests.csproj
    steps:
      - uses: actions/checkout@v3
        with:
          path: .\FailFast

# THIS IS NOT NEEDED WHEN USING A WINDOWS RUNNER
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: 8.0.x

      - name: Restore
        run: |
          dotnet restore "${{ env.SLN }}"
      - name: Build
        id: build-projects
        run: |
          dotnet build "${{ env.SLN }}" --no-restore --configuration Debug

      - name: Test
        id: run-tests
        if: steps.build-projects.outcome == 'success'
        run: |
          dotnet test "${{ env.TESTPRJ }}" --logger "console;verbosity=normal" --no-build --no-restore --configuration Debug
      - run: |
          if: steps.run-tests.outcome == 'success' && github.ref == 'refs/heads/main'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name ${{ github.actor }}
          git add -f "${{ github.workspace }}\Release\FailFast.cs"
          git commit -m 'GH Action Release Artifacts'
          git push origin main
          